### ISSUE TITLE
NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.http.ResponseEntity.getStatusCode()'

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/weblate-spring#59]
It seems that Spring 5 and 6 ResponseEntity#getStatusCode methods are not compatible.

When using this library with Spring 6 / Spring Boot 3 you'll get the following error:

```
org.springframework.http.HttpStatus org.springframework.http.ResponseEntity.getStatusCode()'
java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.http.ResponseEntity.getStatusCode()'
	at at.porscheinformatik.weblate.spring.WeblateMessageSource.loadCodes(WeblateMessageSource.java:407)
	at at.porscheinformatik.weblate.spring.WeblateMessageSource.loadTranslation(WeblateMessageSource.java:335)
	at at.porscheinformatik.weblate.spring.WeblateMessageSource.loadTranslations(WeblateMessageSource.java:305)
	at at.porscheinformatik.weblate.spring.WeblateMessageSource.getAllProperties(WeblateMessageSource.java:439)
```

**Comment by derkoe** [comment]
Spring 6.x broke the API compatibility: https://github.com/spring-projects/spring-framework/issues/29813
